version: '3'

services:
  db:
    image: postgres:15-alpine
    volumes:
     - /opt/postgresql15/postgresql_data:/var/lib/postgresql/data
    env_file:
      - etl/.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    container_name: elasticsearch

  web:
    build: 
      context: ./etl
    volumes:
      - ./etl:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
    restart: always

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./data/static:/var/www/html/static
    depends_on:
      - web